---
application:
  name: "bechde"
  project: "coviseal"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "bechde"
  version: "8.0"
routers:
- name: "main-bechde"
  routes:
  - application_name: "bechde"
    paths:
    - "/*"
